### ISSUE TITLE
Checking for version

### ISSUE THREAD

**Issue by achterbahn** [bezumkin/mmx-forms#1]
Installing mmx-forms as described in README.
CLI is telling me `Using version ^1.1 for mmx/forms`. 
Packagist tells me this is the that this is the latest version (apart from main-dev): https://packagist.org/packages/mmx/forms
But here on Github there is already a version 1.2.0.

- is packagist not up to date?
- FR: would be cool to have a version hint in the extra, like

![image](https://github.com/bezumkin/mmx-forms/assets/1411919/35825ba0-acf4-42ea-8a48-631097fcae33)

**Comment by bezumkin** [comment]
@achterbahn This is was my fault because of wrong version in `composer.json`, now it is fixed!

![Screenshot 2024-04-24 at 15 59 21](https://github.com/bezumkin/mmx-forms/assets/1257284/5fb33e2b-c64a-4862-8c3c-53c444b23f4a)

I'm not closing this issue just to think about showing the version.

**Comment by bezumkin** [comment]
@achterbahn Released new package with version (and update) output.

![Screenshot 2024-04-25 at 14 36 37](https://github.com/bezumkin/mmx-forms/assets/1257284/c448b6d9-25c6-4fad-8dd0-56e53aa7716c) ![Screenshot 2024-04-25 at 14 36 25](https://github.com/bezumkin/mmx-forms/assets/1257284/cd186dd3-b189-4530-8b6e-16951d76805f)
