### ISSUE TITLE
MODX Snippet Parameters for `mmxForms`

### ISSUE THREAD

**Issue by achterbahn** [bezumkin/mmx-forms#2]
Drag'n'Drop a Snippet from the element tree into a resources content field opens the parameters for that snippet. 
But this parameters are not named correctly:

![image](https://github.com/bezumkin/mmx-forms/assets/1411919/9a3413ef-f01a-4d1d-96d5-b1b10768a4dc)

I think it should be:
- id=`1`
- noCSS=`1`

**Comment by bezumkin** [comment]
@achterbahn Fixed in 1.3.0

![Screenshot 2024-04-25 at 14 38 43](https://github.com/bezumkin/mmx-forms/assets/1257284/c9604ff2-b462-4aff-89ea-58b2194e9d5a)

Do not forget to run `composer exec mmx-forms install` after update.
